apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.catalogSource.name }}
  namespace: {{ .Values.catalogSource.namespace }}
  labels:
    {{- include "toolhive-olm.labels" . | nindent 4 }}
spec:
  displayName: {{ .Values.catalogSource.displayName }}
  image: {{ .Values.catalogSource.image }}
  publisher: {{ .Values.catalogSource.publisher }}
  sourceType: grpc
  {{- if .Values.catalogSource.updateStrategy }}
  updateStrategy:
    {{- if .Values.catalogSource.updateStrategy.registryPoll }}
    registryPoll:
      interval: {{ .Values.catalogSource.updateStrategy.registryPoll.interval }}
    {{- end }}
  {{- end }}

